# Generated by Django 5.1.7 on 2025-03-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_apellidos', models.CharField(max_length=255)),
                ('sede', models.CharField(choices=[('L TORRE PANAMA', 'L TORRE PANAMA')], max_length=50)),
                ('unidad_negocio', models.CharField(choices=[('ONCOSALUD', 'ONCOSALUD')], max_length=50)),
                ('linea_movil', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_movil', models.CharField(blank=True, max_length=50, null=True)),
                ('imei_movil', models.IntegerField(blank=True, null=True)),
                ('valor_movil', models.FloatField(blank=True, null=True)),
                ('accesorios_movil', models.CharField(blank=True, max_length=255, null=True)),
                ('linea_fija', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_fija', models.CharField(blank=True, max_length=50, null=True)),
                ('imei_fija', models.IntegerField(blank=True, null=True)),
                ('valor_fija', models.FloatField(blank=True, null=True)),
                ('accesorios_fija', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_tomada', models.ImageField(blank=True, null=True, upload_to='fotos/tomadas/')),
                ('imagen_subida', models.ImageField(blank=True, null=True, upload_to='fotos/subidas/')),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_especialista', models.CharField(choices=[('No Identificado', 'No Identificado'), ('A', 'A')], default='No Identificado', max_length=50)),
            ],
        ),
    ]
