# Generated by Django 5.1.7 on 2025-03-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='imei_movil',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
