# Generated by Django 5.1.4 on 2025-03-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datos', '0002_alter_reporte_imei_movil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='sede',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo_especialista',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='unidad_negocio',
            field=models.CharField(max_length=255),
        ),
    ]
